
#############################################################################################
## The playbook and scripts are stored inside the Ansible server.
## The purpose of this playbook is only to execute the original playbook.
###############################################################################################

---
- name: Monitoring the Linux host(s)
  hosts: ansible_server
  become: false
  tasks:
    - name: Running Monitor script
      command: ansible-playbook /etc/ansible/playbook/linux/monitoring_servers/linuxServerMonitor.yml
...
